services:
  database:
    image: postgres:17.2
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_application
    volumes:
      - ./data:/var/lib/postgresql/data
    